---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 15000
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                host_rewrite: www.google.com
                                cluster: service_google
                    http_filters:
                      - name: envoy.router
      clusters:
        - name: service_google
          connect_timeout: 0.25s
          type: LOGICAL_DNS
          # Comment out the following line to test on v6 networks
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: service_google
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: www.google.com
                          port_value: 443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
              sni: www.google.com

---
apiVersion: batch/v1
kind: Job
metadata:
  name: scuttle
  labels:
    app: scuttle
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: scuttle
    spec:
      restartPolicy: Never
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
      containers:
        - name: scuttle
          image: scuttle:local
          env:
            - name: ENVOY_ADMIN_API
              value: "http://127.0.0.1:15000"
            - name: ISTIO_QUIT_API
              value: "http://127.0.0.1:15000"
            - name: SCUTTLE_LOGGING
              value: "true"
          command:
            - /scuttle
            - /bin/sh
            - -c
            - |
              for i in `seq 10`
              do
                echo executing
                sleep 1
              done
              echo "shutting down..."
        - name: envoy
          image: envoyproxy/envoy:v1.13.1
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 15000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy

